### ISSUE TITLE
Unique password policy for each tenant

### ISSUE THREAD

**Issue by cocadepoma** [anarsultanov/keycloak-multi-tenancy#10]
Hello, I am planning to implement Keycloak in a project and I would like to have different password policies defined for each tenant, does this extension allow me to do it?

Thank you so much for your attention.

**Comment by anarsultanov** [comment]
Hello @soyl3y3nd4,
 
Unfortunately, the extension does not currently support different password policies for each tenant. However, you can still implement tenant-specific Identity Providers (IDPs) and allow tenants to manage their own policies through their respective IDPs. 

If you have any further questions or need assistance, feel free to ask.

**Comment by soyl3y3nd4** [comment]
Hi @anarsultanov, thank you very much for your answer.

Where can I find an example of how to build what you said? 

> tenant-specific Identity Providers (IDPs) and allow tenants to manage their own policies through their respective IDPs

I plan to have a Realm with several clients (frontends and backends) and then every customer with their own Realm, users, password policies, etc... is this possible to do in Keycloak? 

If this is possible, for example, if a user is not authenticated and tries to enter into a protected client, where it should be redirected, which Realm? 

Sorry for my confusion, and thanks for your help.

**Comment by anarsultanov** [comment]
Hi @soyl3y3nd4, no problem at all! 

It looks like your use case is completely different from the intended purpose of this extension.

As for your question, I'm not sure if your idea is possible, as users and clients are realm-specific in Keycloak.

For more guidance, I recommend checking the Keycloak documentation or reaching out to the Keycloak community.

Feel free to ask if you have any more questions!
