### ISSUE TITLE
REALM_ID, USER_ID, TENANT_ID with wrong varchar length 

### ISSUE THREAD

**Issue by paolociliberto** [anarsultanov/keycloak-multi-tenancy#14]
Hello, on https://github.com/anarsultanov/keycloak-multi-tenancy/blob/main/src/main/resources/META-INF/keycloak-multi-tenancy-changelog-20221217-2113.xml the ids REALM_ID, USER_ID, TENANT_ID are varchar(255)  on line 14, 26 and 29. They should be 36. Indeed, when start on sql server it break everything and the entiry keycloack doesn't start. I fixed in my pc, i cannot push a branch or a suggestion on your repo so i write here. Also the plugin you deployed are broken with sql server. i suggest to fix.

Kind Regards
Paolo

**Comment by anarsultanov** [comment]
Hi Paolo,

Thank you for highlighting the SQL Server compatibility issue. 

I've addressed the column length inconsistency in a new pull request, which you can find here: https://github.com/anarsultanov/keycloak-multi-tenancy/pull/16.
Could you please review the changes and confirm if they resolve your issue?

Best regards,
Anar
