### ISSUE TITLE
Rename a tenant

### ISSUE THREAD

**Issue by codecooper** [anarsultanov/keycloak-multi-tenancy#30]
This is more of a feature request. Is it possible to rename a tenant? Ideally this would be a `PUT` endpoint on the API. This would be useful for users who did not know what the purpose of entering the tenant name and may want to change it in the future as they start adding other members.

**Comment by anarsultanov** [comment]
Hi @codecooper,
I agree that introducing the ability to rename a tenant is a valuable addition. I'll work on implementing this feature soon. Thanks for the suggestion!
