### ISSUE TITLE
OpenAPI/Swagger documentation

### ISSUE THREAD

**Issue by codecooper** [anarsultanov/keycloak-multi-tenancy#34]
First off, thank you have having a swagger doc. It really helps with auto-generating client code to work with it. That being said.  I have noticed some inconsistencies. 

- PUT: /tenants/{tenantId}
  - You have a response type of 200 in the docs, however the actual response if 204
- GET: /tenants/{tenantId}/memberships
  - The `user` object in the response is not defined as a schema.

There are others as well. I guess the ask is a review of the request payloads, response models, and status codes to ensure the API docs match the actual results.

**Comment by anarsultanov** [comment]
Thank you for pointing out the discrepancies, @codecooper. I've updated the OpenAPI schema.
