### ISSUE TITLE
Problem trying to remove tenant

### ISSUE THREAD

**Issue by jbergesn** [anarsultanov/keycloak-multi-tenancy#4]
Hi @anarsultanov, I am having problems when I try to delete a created tenant.  The error seems to be caused by the existing relationships between the tables, and when trying to delete a tenant it tells me that there are relationships with other tables on the record that I am trying to delete due to the foreign key constraint.

I attach an image where you can see the error it is giving me. 
![image](https://github.com/anarsultanov/keycloak-multi-tenancy/assets/143794039/6d4ca1dc-0dd3-4109-b147-4b245a766754)

Do you know if I'm doing something wrong?

Thank you very much in advance

**Comment by anarsultanov** [comment]
Hi @jbergesn,

It seems your issue may be related to https://github.com/anarsultanov/keycloak-multi-tenancy/issues/2. 

To potentially fix it, please try rebuilding the extension from the latest main branch or use the most recent [release](https://github.com/anarsultanov/keycloak-multi-tenancy/releases).
Please let me know if it resolves your problem.
